### ISSUE TITLE
使用vultr服务自动分配ipv6,绑定ip失败

### ISSUE THREAD

**Issue by gordonchanfz** [knva/kproxy#1]
使用vultr服务自动分配ipv6,绑定ip失败，信息如下，请不吝赐教，谢谢。 
http: proxy error: dial tcp [2001:19f0:0:4d4c:7858:bab4:370e:988b]:0->[2606:4700:4400::ac40:9b8d]:443: bind: cannot assign requested address

**Comment by gordonchanfz** [comment]
> 使用vultr服务自动分配ipv6,绑定ip失败，信息如下，请不吝赐教，谢谢。 http: proxy error: dial tcp [2001:19f0:0:4d4c:7858:bab4:370e:988b]:0->[2606:4700:4400::ac40:9b8d]:443: bind: cannot assign requested address

搞定了，套接和路由没配，谢谢

**Comment by knva** [comment]
跑个仓库里的脚本就行了，是在不行，按照脚本的内容手动配置一下
